from enum import StrEnum
from typing import Any

from pydantic import Field

from app.contracts.dto.common import ContractModel


class ErrorCode(StrEnum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
    RESOURCE_VERSION_CONFLICT = "RESOURCE_VERSION_CONFLICT"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

    VEHICLE_NOT_AVAILABLE = "VEHICLE_NOT_AVAILABLE"
    VEHICLE_RETIRED = "VEHICLE_RETIRED"
    VEHICLE_IN_MAINTENANCE = "VEHICLE_IN_MAINTENANCE"
    VEHICLE_CAPACITY_EXCEEDED = "VEHICLE_CAPACITY_EXCEEDED"
    DRIVER_NOT_AVAILABLE = "DRIVER_NOT_AVAILABLE"
    DRIVER_SUSPENDED = "DRIVER_SUSPENDED"
    DRIVER_LICENCE_EXPIRED = "DRIVER_LICENCE_EXPIRED"
    DRIVER_LICENCE_INCOMPATIBLE = "DRIVER_LICENCE_INCOMPATIBLE"
    TRIP_NOT_DRAFT = "TRIP_NOT_DRAFT"
    TRIP_NOT_DISPATCHED = "TRIP_NOT_DISPATCHED"
    TRIP_ALREADY_TERMINAL = "TRIP_ALREADY_TERMINAL"
    ODOMETER_DECREASE_NOT_ALLOWED = "ODOMETER_DECREASE_NOT_ALLOWED"
    ACTIVE_MAINTENANCE_EXISTS = "ACTIVE_MAINTENANCE_EXISTS"
    EXPENSE_ALREADY_REVIEWED = "EXPENSE_ALREADY_REVIEWED"
    DOCUMENT_UPLOAD_INVALID = "DOCUMENT_UPLOAD_INVALID"
    REPORT_GENERATION_FAILED = "REPORT_GENERATION_FAILED"


class ErrorResponse(ContractModel):
    code: str
    message: str
    details: dict[str, Any] = Field(default_factory=dict)
    request_id: str
